baseURL = "https://jonjlee.github.io/cope-mockup/"
languageCode = "en-us"
title = "Compassionate Options for Pediatric EMS"
theme = "hugo-universal-theme"
publishDir = "docs"

[menu]
[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier = "videos"
    name = "Videos"
    url  = "/videos/"
    weight = 2

[[menu.main]]
    identifier = "resources"
    name = "Resources"
    url  = "/resources/"
    weight = 3

[[menu.main]]
    identifier = "about"
    name = "About Us"
    url  = "/contact"
    weight = 4


[params]
    viewMorePostLink = "/blog/"
    author = "Jonathan Lee"
    mainSections = ["blog"]

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    about_us = "<p>COPE was supported by the Health Resources and Services Administration (HRSA), Maternal and Child Health Bureau (MCHB), Emergency Medical Services for Children (EMSC) Targeted Issues grant program, Grant No. H34MC26204 for $849,246. This information or content and conclusions are those of the author and should not be construed as the official position or policy of, nor should any endorsements be inferred by HRSA, HHS, or the U.S. government.</p>"
    copyright = "Copyright (c) 2021. All rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/cope-logo.jpg"
    logo_small = "img/cope-logo.jpg"
    address = """<p class="text-uppercase"><strong>Kentucky Board of Emergency Medical Services</strong>
        <br>2464 Fortune Drive,
        <br>Suite 195
        <br>Lexington, KY 40509
      </p>
      """

[params.carousel]
    enable = true

[params.features]
    enable = true
    # All features are defined in their own files in data/features
